# Generated by Django 2.2.3 on 2019-11-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
